# https://www.playframework.com/documentation/latest/Configuration
play.http.secret.key="changethissupersecretkeyforsplitbiteinprod"

redis.url = "redis://localhost:6379"
redis.url = ${?REDIS_URL}

play.modules.enabled += "modules.ActorModule"

play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  allowedOrigins = null
  allowedHttpMethods = null
  allowedHttpHeaders = null
  preflightMaxAge = 3 days
}
